-- 회원 테이블 생성.
CREATE TABLE IF NOT EXISTS USERS
(
    USERNO    BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID        VARCHAR(30)  NOT NULL UNIQUE,
    PW        VARCHAR(30)  NOT NULL,
    NAME      VARCHAR(30)  NOT NULL,
    ADDR      VARCHAR(255) NOT NULL,
    SLEEPFLAG BOOLEAN      NOT NULL DEFAULT FALSE,
    REGDATE   DATETIME     NOT NULL,
    UPDDATE   DATETIME
);

-- jwt 토큰 테이블 생성.
CREATE TABLE IF NOT EXISTS AUTHTOKEN
(
    USERID       VARCHAR(30) UNIQUE,
    ACCESSTOKEN  VARCHAR(1000),
    REFRESHTOKEN VARCHAR(1000),
    FOREIGN KEY (USERID) REFERENCES USERS (ID)
);

-- 상품 테이블 생성.
CREATE TABLE IF NOT EXISTS PRODUCTINFO
(
    PRODSEQNO BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODNAME  VARCHAR(255) NOT NULL,
    PRICE     VARCHAR(255) NOT NULL,
    PROVIDER  VARCHAR(255) NOT NULL,
    INFO      TEXT, -- NVARCHAR(MAX) 대신 TEXT 사용
    USEFLAG   BOOLEAN      NOT NULL,
    REGDATE   DATETIME     NOT NULL,
    UPDDATE   DATETIME
);

-- 주문 테이블 생성.
CREATE TABLE IF NOT EXISTS ORDERINFO
(
    ORDERNO   BIGINT PRIMARY KEY,
    USERID    VARCHAR(30)  NOT NULL,
    USERNAME  VARCHAR(30)  NOT NULL,
    USERADDR  VARCHAR(255) NOT NULL,
    PRODSEQNO BIGINT       NOT NULL,
    PRODNAME  VARCHAR(255) NOT NULL,
    PRODPRICE VARCHAR(255) NOT NULL,
    REGDATE   DATETIME     NOT NULL,
    UPDDATE   DATETIME,
    FOREIGN KEY (USERID) REFERENCES USERS (ID),
    FOREIGN KEY (PRODSEQNO) REFERENCES PRODUCTINFO (PRODSEQNO)
);

-- 배송지 테이블 생성.
CREATE TABLE IF NOT EXISTS DELIVERYADDR
(
    DELIADDRNO  BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERID      VARCHAR(30)  NOT NULL,
    ADDRALIAS   VARCHAR(10)  NOT NULL,
    DELIADDR    VARCHAR(255) NOT NULL,
    DEFDELIADDR BOOLEAN      NOT NULL DEFAULT FALSE,
    FOREIGN KEY (USERID) REFERENCES USERS (ID)
);

-- 회원 데이터 삽입.
INSERT INTO USERS (ID, PW, NAME, ADDR, REGDATE)
SELECT *
FROM (SELECT 'test1' AS ID, '1234' AS PW, 'John Doe' AS NAME, '경기도 용인시 어쩌구 저쩌구' AS ADDR, NOW() AS REGDATE
      UNION ALL
      SELECT 'test2', '1234', 'Jane Smith', '경기도 화성시 어쩌구 저쩌구', NOW()
      UNION ALL
      SELECT 'test3', '1234', 'Alice Johnson', '경기도 성남시 어쩌구 저쩌구', NOW()
      UNION ALL
      SELECT 'test4', '1234', 'Bob Brown', '서울 중랑구 어쩌구 저쩌구', NOW()
      UNION ALL
      SELECT 'test5', '1234', 'Charlie Green', '경기도 구리시 어쩌구 저쩌구', NOW()) AS TEMP
WHERE NOT EXISTS (SELECT 1 FROM USERS);

-- 상품 데이터 삽입.
INSERT INTO PRODUCTINFO (PRODNAME, PRICE, PROVIDER, INFO, USEFLAG, REGDATE)
SELECT *
FROM (SELECT '티셔츠'        AS PRODNAME,
             '25000'      AS PRICE,
             '마프'         AS PROVIDER,
             '평범한 티 입니다.' AS INFO,
             TRUE         AS USEFLAG,
             NOW()        AS REGDATE
      UNION ALL
      SELECT '티셔츠1', '25000', '마프', '평범한 티 입니다.', TRUE, NOW()
      UNION ALL
      SELECT '티셔츠2', '25000', '마프', '평범한 티 입니다.', TRUE, NOW()
      UNION ALL
      SELECT '티셔츠3', '25000', '마프', '평범한 티 입니다.', TRUE, NOW()
      UNION ALL
      SELECT '티셔츠4', '25000', '마프', '평범한 티 입니다.', TRUE, NOW()) AS TEMP
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTINFO);
